export const robots=[
    {
        id:1,
        name:'Akash',
        username:'akki',
        email:'akki@gmail.com'
    },
    {
        id:2,
        name:'Danish',
        username:'softineer',
        email:'softineer@gmail.com'
    },
    {
        id:3,
        name:'Zeeshan',
        username:'Zash',
        email:'zash@gmail.com'
    },
    {
        id:4,
        name:'Anshuman',
        username:'Anshu',
        email:'Anshu@gmail.com'
    },
    {
        id:5,
        name:'Amit',
        username:'starter',
        email:'amit@gmail.com'
    },
    {
        id:6,
        name:'Zulfikar',
        username:'zulfi',
        email:'zulfi@gmail.com'
    },
    {
        id:7,
        name:'Ziyaul',
        username:'Arshi',
        email:'arshi@gmail.com'
    },
    {
        id:8,
        name:'Tanveer',
        username:'tannu',
        email:'Tannu@gmail.com'
    },
    {
        id:9,
        name:'Faizan',
        username:'faiz',
        email:'faiz@gmail.com'
    },
    {
        id:10,
        name:'Azhar',
        username:'ajju',
        email:'ajju@gmail.com'
    },
    {
        id:11,
        name:'kaamran',
        username:'kammu',
        email:'kammu@gmail.com'
    },
    {
        id:12,
        name:'Akbar',
        username:'akku',
        email:'akku@gmail.com'
    },
    
]